# Generated by Django 6.0.7 on 2026-07-12 10:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['ticker'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sell_date', models.DateField()),
                ('qty_sold', models.DecimalField(decimal_places=8, max_digits=18)),
                ('sale_price_usd', models.DecimalField(decimal_places=6, max_digits=14)),
                ('fee_usd', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('fx_rate_usd_thb', models.DecimalField(decimal_places=4, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to=settings.AUTH_USER_MODEL)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='portfolio.symbol')),
            ],
            options={
                'ordering': ['-sell_date'],
            },
        ),
        migrations.CreateModel(
            name='StockLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_date', models.DateField()),
                ('price_usd', models.DecimalField(decimal_places=6, max_digits=14)),
                ('qty', models.DecimalField(decimal_places=8, max_digits=18)),
                ('fx_rate_usd_thb', models.DecimalField(decimal_places=4, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_lots', to=settings.AUTH_USER_MODEL)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lots', to='portfolio.symbol')),
            ],
            options={
                'ordering': ['buy_date', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaleAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_allocated', models.DecimalField(decimal_places=8, max_digits=18)),
                ('cost_basis_thb', models.DecimalField(decimal_places=4, max_digits=14)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='portfolio.sale')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='portfolio.stocklot')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('qty_allocated__gt', 0)), name='qty_allocated_positive')],
            },
        ),
    ]
