# Generated by Django 6.0.7 on 2026-07-12 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='evidence',
            field=models.ImageField(blank=True, null=True, upload_to='sale_evidence/'),
        ),
        migrations.AddField(
            model_name='stocklot',
            name='evidence',
            field=models.ImageField(blank=True, null=True, upload_to='lot_evidence/'),
        ),
    ]
