# Generated by Django 6.0.7 on 2026-07-20 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_sale_evidence_stocklot_evidence'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ['sell_date', 'created_at']},
        ),
    ]
