# Generated by Django 6.0.7 on 2026-07-20 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_sale_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ['sell_date']},
        ),
        migrations.AlterModelOptions(
            name='stocklot',
            options={'ordering': ['buy_date']},
        ),
    ]
