# Generated by Django 6.0.7 on 2026-07-20 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_sale_options_alter_stocklot_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ['sell_date', 'created_at']},
        ),
        migrations.AlterModelOptions(
            name='stocklot',
            options={'ordering': ['buy_date', 'created_at']},
        ),
    ]
